name: helloWorld
on: push
jobs: 
    hello:
        runs-on: ubuntu-latest
        env:
         ACTOR: ${{ 'hello' }}

        steps:
            - run: echo "${ACTOR}" 
              if: ${{contains(github.run_id,'1')}}
            - uses: actions/checkout@v4
            