name: helloWorld
on: push
jobs: 
    hello:
        runs-on: ubuntu-latest
        env:
         ACTOR: '[ { "name": "apple", "quantity": 1 }, { "name": "orange", "quantity": 2 },{ "name": "pear", "quantity": 1 }]'
        steps:
            - run: echo "${ACTOR.*.name}" 
            - uses: actions/checkout@v4
            