name: helloWorld
on: push
jobs: 
    hello:
        runs-on: ubuntu-latest
        env:
         ACTOR: ${{ contains(github.event.issue.labels.*.name,'bug') }}
        steps:
            - run: echo "${ACTOR}" 
            - uses: actions/checkout@v4
            