name: helloWorld
on: push
jobs: 
    hello:
        runs-on: ubuntu-latest
        env:
         EVENT: ${{ github.event.*.html_url}}
        steps:
            - run: echo "${EVENT}" 
            - uses: actions/checkout@v4
            