name: helloWorld
on: push
jobs: 
    hello:
        runs-on: ubuntu-latest
        env:
         ACTOR: ${{ github.event.issue }}
        steps:
            - run: echo "${ACTOR}" 
            - uses: actions/checkout@v4
            