name: helloWorld
on: push
jobs: 
    hello:
        runs-on: ubuntu-latest
        

        env:
          PASSWORDD: ${{secrets.PASSWORD}}
        steps:
         - run: echo "${PASSWORD}"
            