name: helloWorld
on: push
jobs: 
    hello:
        runs-on: ubuntu-latest
        

        steps:
            - run: echo "hel" 
              if: ${{contains(github.run_id,'g1')}}
            - uses: actions/checkout@v4
            