name: helloWorld
on: push
jobs: 
    hello:
        runs-on: ubuntu-latest
        env:
         ACTOR: ${{ format('nozaki,ntama.','Hi','world')}}
        steps:
            - run: echo "${ACTOR}" 
            - uses: actions/checkout@v4
            